Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: com.jracademic.coupon.lambda.coupon.GetSingleCouponRequestHandler
      CodeUri: D:\developer\JRAcademic\LambdaCouponService\coupon
      Runtime: java17
      Architectures:
        - x86_64